name: Test locknock

on: [push]

jobs:
  go-build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Test with Go
      run: go test -v ./...

    - name: Build with Go
      run: go build -v ./...
